---
# vars file for roles/common
common_packages:
  - ntp
  - git
  - vim
  - unzip
  - curl

apache_document_root: /var/www/html
apache_server_name: mywebsite.local
allowed_ips:
  - 192.168.1.10
  - 192.168.1.20
  - 192.168.1.30

